spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baran
    username: baran
    password: baran
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
logging:
  level:
    root: INFO
    net.javacrumbs.shedlock: DEBUG
    com.example.tasklet: DEBUG   # DEBUG level to view logs within each Tasklet

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3               # Maximum number of retry attempts for each failed call
        wait-duration: 2s             # Waiting time between retry attempts
    instances:
      initiatePaymentRetry:
        base-config: default          # Configures Retry for InitiatePayment using default settings
      verifyPaymentRetry:
        base-config: default          # Configures Retry for VerifyPayment using default settings
      completePaymentRetry:
        base-config: default          # Configures Retry for CompletePayment using default settings

  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50     # Circuit Breaker will open if failure rate reaches 50%
        wait-duration-in-open-state: 5s # Time the Circuit Breaker remains open before attempting to close again
    instances:
      initiatePaymentCircuitBreaker:
        base-config: default           # Configures Circuit Breaker for InitiatePayment using default settings
      verifyPaymentCircuitBreaker:
        base-config: default           # Configures Circuit Breaker for VerifyPayment using default settings
      completePaymentCircuitBreaker:
        base-config: default           # Configures Circuit Breaker for CompletePayment using default settings
